project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub Python for Geoscience"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Introduction"
          href: 00-intro.html
        - text: "Fundamentals"
          href: notebooks/01a-fundamentals.html

      - text: "Session 2"
        menu:
        - text: "Useful Python packages for different data types"
          href: notebooks/01b-dataframes.html

      - text: "Session 3"
        menu:
        - text: "Numerical Approaches"
          href: notebooks/02b-Clustering.html
        - text: "Machine Learning Workflow"
          href: notebooks/03-ML_workflow.html

      - text: "Session 4"
        menu:
        - text: "Efficient Python Methods"
          href: notebooks/04a-SimpleSpeedUps.html
        - text: "Bonus: Matplotlib and Mapping with Cartopy"
          href: notebooks/02a-mapping.html
        - text: "Bonus: Deep Learning & Time Series"
          href: notebooks/03b-DeepLearningTS.html
        - text: "Bonus: Dask data frames"
          href: notebooks/04b-DaskDataframes.html
        - text: "Bonus: Merging Text Tables"
          href: notebooks/merge.html
        - text: "Bonus: Working with PDF files"
          href: notebooks/PDF2Python.html
        - text: "Bonus: segy2text2segy"
          href: notebooks/text2segy.html
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




