project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub Python for Geoscience"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Introduction"
          href: 00-intro.html
        - text: "Fundamentals"
          href: notebooks/01a-fundamentals.html

      - text: "Session 2"
        menu:
        - text: "Useful Python packages for different data types"
          href: notebooks/01b-dataframes.html

      - text: "Session 3"
        menu:
        - text: "Numerical Approaches"
          href: 02b-Clustering.html
        - text: "Machine Learning Workflow"
          href: notebooks/03-ML_workflow.html

      - text: "Session 4"
        menu:
        - text: "Efficient Python Methods"
          href: notebooks/04a-SimpleSpeedUps.html
        - text: "Bonus: Matplotlib and Mapping with Cartopy"
          href: notebooks/02a-mapping.html
        - text: "Bonus: Deep Learning & Time Series"
          href: notebooks/03b-DeepLearningTS.html
        - text: "Bonus: Dask data frames"
          href: notebooks/04b-DaskDataframes.html

format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github



