name: geopy
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.9
  - numpy=1.18
  - pip
  - pandas=1.2
  - matplotlib=3.3
  - pyshp=2.1
  - obspy=1.2
  - scipy=1.5
  - scikit-learn=1.0
  - cartopy=0.18
  - pip:
    - lasio==0.28
    - tensorflow==2.3
    - dask[complete]
    - notebook==6.2.0
    - jupyterlab==2.2.9
    - cython


python=3.9 scikit-learn=0.23.2 seaborn=0.11.2 numpy=1.20.3 pandas=1.2.3 scipy=1.5.3 
pip install jupyterlab==3.3.3 pyshp==2.1.3 shapely==1.8.1 upsetplot==0.6.0