name: geopy
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.7
  - numpy=1.18
  - pip
  - pandas=1.0.1
  - matplotlib=3.3.2
  - pyshp=2.1.3
  - obspy=1.2.2
  - scipy=1.4.1
  - scikit-learn=0.23
  - cartopy=0.18
  - pip:
    - lasio==0.28
    - tensorflow==2.3
    - dask[complete]
    - notebook==6.2.0
    - jupyterlab==2.2.9
    - cython
