name: geopy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - seaborn
  - obspy
  - pyshp
  - scikit-learn
  - scipy
  - cartopy
  - upsetplot
  - pandas
  - jupyter
  - pip
  - pip:
    - lasio
